name: Formatting

on:
  push:
    branches: [main]

jobs:
  check-formatting:
    runs-on: fedora-latest
    
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      
      - name: Install clang-format
        run: sudo dnf install -y clang-format

      - name: Veriry ubuntu version
        run: cat /etc/fedora-release

      - name: Verify clang-format installation
        run: clang-format --version

      - name: Run clang-format
        run: clang-format -n -Werror $(find . -regex ".*\.\(cpp\|hpp\)")
