name: Formatting

on:
  push:
    branches: [main]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      
      - name: Run clang-format
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace fedora:latest /bin/bash -c "
          dnf install -y clang-tools-extra && \
          clang-format --version && \
          clang-format -n -Werror \$(find /workspace -regex '.*\\.\(cpp\\|hpp\\)')
          "

      # - name: Install clang-format
      #   run: sudo dnf install -y clang-format

      # - name: Veriry ubuntu version
      #   run: cat /etc/fedora-release

      # - name: Verify clang-format installation
      #   run: clang-format --version

      # - name: Run clang-format
      #   run: clang-format -n -Werror $(find . -regex ".*\.\(cpp\|hpp\)")
