name: Formatting

on:
  push:
    branches: [main]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      
      # The following trick exists only because Ubuntu doesn't support the latest version of clang-format
      # and because the fedora runner I tried to used took 30min to do nothing so I had to stop it.
      - name: Run clang-format
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace fedora:latest /bin/bash -c "
          dnf install -y clang-tools-extra > /dev/null 2>&1 && \
          echo '-' && \
          clang-format --version && \
          echo '-' && \
          echo 'Errors below if any' && \
          echo '-' && \
          clang-format -n -Werror \$(find /workspace -regex '.*\\.\(cpp\\|hpp\\)')
          "

      # This should be the good way of doing it
      # - name: Install clang-format
      #   run: sudo dnf install -y clang-format

      # - name: Run clang-format
      #   run: clang-format -n -Werror $(find . -regex ".*\.\(cpp\|hpp\)")
